### ISSUE TITLE
Request for Upload "Efficiency" Indication

### ISSUE THREAD

**Issue by arizonajon** [RIEI/WiFiDB#2]
Request to augment an existing field on the WiFidB "Files Already Imported" page, where in addition to already showing the number of APs and GPS positions in a given uploaded file, that a new field called "New APs" or similar shows the user how many or what percent of the APs collected in that file are new to the WiFidB.

**Comment by pferland** [comment]
Finished the backed calculations for the New AP Percentage. Added a new column to the user_imports table `NewAPPercent` its an int(255).

Next step is to add the view to the front end and the API fetching of import data.

**Comment by pferland** [comment]
All the code is in place, just need to do a merge with the prod code and make sure it doesn't break anything.

**Comment by pferland** [comment]
Created a fork of andrews prod code and merged my working branch with it to test against prod code.

**Comment by arizonajon** [comment]
Look forward to playing with it shortly - am here in Chicago and racking up a lot of new APs with my little setup using my refurb winbook, TP-Link dual band Usb wifi, and gps

**Comment by pferland** [comment]
I also am going to make a script to calculate and populate the New AP Percentage for all the old imports also.

**Comment by pferland** [comment]
Script to calculate and update the old imports created. just need to get @acalcutt  to run it on the prod servers, to get the data populated.

**Comment by pferland** [comment]
Fixed the bad mathing calculating the new ap percentage. code is comited to the 0.30b1_PF_Prod branch.

**Comment by pferland** [comment]
Andrew has applied this to Prod, Closing issue.
